services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-dev
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config:Z
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: always

volumes:
  mosquitto_data:
  mosquitto_log: